# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) 2024 Advanced Micro Devices, Inc.

name: Install dependencies
description: Install build and test dependencies for TCPDirect
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: sh
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential perl
